package com.example.Hackathon.dto;

public enum BotState {
    MAIN_MENU,
    AWAITING_CUSTOMER_ID_BALANCE,
    AWAITING_CUSTOMER_ID_COMPLAINT,
    AWAITING_CATEGORY,
    AWAITING_DESCRIPTION,
    AWAITING_MEDIA_OR_CONFIRMATION,
    AWAITING_COMPLAINT_ID
}
